modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="alzos_mod"
version="0.1"
displayName="Alzo's Mod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Tameable, AlzokenFox"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.alzos_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.alzos_mod]]
    modId="pehkui"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration